port: 9751
redis: "localhost:6379"

private_key: "MiTeV7dg3qWeH52us+FaZOs1RfaEyIkWWqWrH+00b0o:WRIA6TJNBO46T5KFEZHQDYDUAQWU326DJ7SBHWGH3DIPM2KQWPRA"

threshold: 2
quorum: [
  SYYNCHHUXYOBD6IYXSAHVDBY7C2KWFMI6737Z432HOJSRXSU2I2Q,
  UJVDQVK4F64M3ELXEWRNOD4NVP2MZQEFQNHJEKPG4HRALIZCIUFQ,
  JR67VYFA7ZV2JKQ3WWI7UXCGXXM7L4ABUBVVOH3L43SXZ67VID6Q,
]

addresses:
  "localhost:9752": SYYNCHHUXYOBD6IYXSAHVDBY7C2KWFMI6737Z432HOJSRXSU2I2Q
  "localhost:9753": UJVDQVK4F64M3ELXEWRNOD4NVP2MZQEFQNHJEKPG4HRALIZCIUFQ
  "localhost:9754": JR67VYFA7ZV2JKQ3WWI7UXCGXXM7L4ABUBVVOH3L43SXZ67VID6Q
