port: 9754
redis: "localhost:6382"

private_key: "pBpNIdB8wAf4l9v2EI2OWbUkT6ShH2JsIAU6IWLkyW0:JR67VYFA7ZV2JKQ3WWI7UXCGXXM7L4ABUBVVOH3L43SXZ67VID6Q"

threshold: 2
quorum: [
  WRIA6TJNBO46T5KFEZHQDYDUAQWU326DJ7SBHWGH3DIPM2KQWPRA,
  SYYNCHHUXYOBD6IYXSAHVDBY7C2KWFMI6737Z432HOJSRXSU2I2Q,
  UJVDQVK4F64M3ELXEWRNOD4NVP2MZQEFQNHJEKPG4HRALIZCIUFQ,
]

addresses:
  "localhost:9751": WRIA6TJNBO46T5KFEZHQDYDUAQWU326DJ7SBHWGH3DIPM2KQWPRA
  "localhost:9752": SYYNCHHUXYOBD6IYXSAHVDBY7C2KWFMI6737Z432HOJSRXSU2I2Q
  "localhost:9753": UJVDQVK4F64M3ELXEWRNOD4NVP2MZQEFQNHJEKPG4HRALIZCIUFQ
