port: 9752
redis: "localhost:6380"

private_key: "qHp/vmkgzy6Bq69r+0PZUeF3x/FbiJm6If1NzM9no1s:SYYNCHHUXYOBD6IYXSAHVDBY7C2KWFMI6737Z432HOJSRXSU2I2Q"

threshold: 2
quorum: [
  WRIA6TJNBO46T5KFEZHQDYDUAQWU326DJ7SBHWGH3DIPM2KQWPRA,
  UJVDQVK4F64M3ELXEWRNOD4NVP2MZQEFQNHJEKPG4HRALIZCIUFQ,
  JR67VYFA7ZV2JKQ3WWI7UXCGXXM7L4ABUBVVOH3L43SXZ67VID6Q,
]

addresses:
  "localhost:9751": WRIA6TJNBO46T5KFEZHQDYDUAQWU326DJ7SBHWGH3DIPM2KQWPRA
  "localhost:9753": UJVDQVK4F64M3ELXEWRNOD4NVP2MZQEFQNHJEKPG4HRALIZCIUFQ
  "localhost:9754": JR67VYFA7ZV2JKQ3WWI7UXCGXXM7L4ABUBVVOH3L43SXZ67VID6Q
