port: 9753
redis: "localhost:6381"

private_key: "EwttVdqGvvvMyF7k1Yw9wkgBzKn9Gvbb1bZybQLFnt4:UJVDQVK4F64M3ELXEWRNOD4NVP2MZQEFQNHJEKPG4HRALIZCIUFQ"

threshold: 2
quorum: [
  WRIA6TJNBO46T5KFEZHQDYDUAQWU326DJ7SBHWGH3DIPM2KQWPRA,
  SYYNCHHUXYOBD6IYXSAHVDBY7C2KWFMI6737Z432HOJSRXSU2I2Q,
  JR67VYFA7ZV2JKQ3WWI7UXCGXXM7L4ABUBVVOH3L43SXZ67VID6Q,
]

addresses:
  "localhost:9751": WRIA6TJNBO46T5KFEZHQDYDUAQWU326DJ7SBHWGH3DIPM2KQWPRA
  "localhost:9752": SYYNCHHUXYOBD6IYXSAHVDBY7C2KWFMI6737Z432HOJSRXSU2I2Q
  "localhost:9754": JR67VYFA7ZV2JKQ3WWI7UXCGXXM7L4ABUBVVOH3L43SXZ67VID6Q